# Generated by Django 3.1.6 on 2022-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_offers', '0002_offer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='payment_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='payment_min',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rate_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rate_min',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='term_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='term_min',
        ),
        migrations.AddField(
            model_name='offer',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Ставка, %'),
            preserve_default=False,
        ),
    ]
