# Generated by Django 3.1.6 on 2022-06-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_offers', '0003_auto_20220602_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rate',
            field=models.FloatField(verbose_name='Ставка'),
        ),
    ]
