# Generated by Django 3.1.6 on 2022-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_offers', '0005_auto_20220603_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='payment_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='payment_min',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rate_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rate_min',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='term_max',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='term_min',
        ),
        migrations.AlterField(
            model_name='offer',
            name='bank_name',
            field=models.CharField(default=0, max_length=128, verbose_name='Наименование банка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Платеж в месяц'),
        ),
    ]
