# Generated by Django 3.1.6 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_offers', '0006_auto_20220603_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='term_max',
            field=models.IntegerField(default=0, verbose_name='Срок ипотеки, ДО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='term_min',
            field=models.IntegerField(default=10, verbose_name='Срок ипотеки, ОТ'),
            preserve_default=False,
        ),
    ]
