# Generated by Django 3.1.6 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage_offers', '0007_auto_20220603_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='payment_max',
            field=models.IntegerField(default=30, verbose_name='Сумма кредита, ДО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_min',
            field=models.IntegerField(default=10, verbose_name='Сумма кредита, ОТ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='rate_max',
            field=models.FloatField(default=10000000, verbose_name='Ставка, ДО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='rate_min',
            field=models.FloatField(default=1000000, verbose_name='Ставка, ОТ'),
            preserve_default=False,
        ),
    ]
